# All available configuration can be found here:
# https://www.algolia.com/doc/api-client/symfony/configuration/
algolia_search:
    prefix: '%env(APP_ENV)%_'
    doctrineSubscribedEvents: []  # disable doctrine events (turn off realtime sync)
    indices:
       - name: companyName
         class: App\Entity\Company
         enable_serializer_groups: true

#       - name: comments
#         class: App\Entity\Comment

