security:
    encoders:
        App\Entity\User: bcrypt
        App\Entity\Company: bcrypt
        App\Entity\Employee: bcrypt
        App\Entity\Administrator: bcrypt

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                #always_use_default_target_path: true
                #default_target_path: /main

            logout:
                path: /logout
                target: /



    access_control:
        - { path: ^/main, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/company/, role: ROLE_COMPANY }
        - { path: ^/employee/, role: ROLE_EMPLOYEE }

    providers:
        chain_provider:
            chain:
                providers: [user, company, employee]
        user:
            entity: { class: App\Entity\User }
        company:
            entity: { class: App\Entity\Company, property: email }
        employee:
            entity: { class: App\Entity\Employee, property: email }